### ISSUE TITLE
Create a can-globals package to handle stateful globals and probably feature detection

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-globals#1]
- [x] - [Write up API](https://github.com/canjs/can-globals/blob/tests/docs.md), get it reviewed by core team. 
- [x] - Check can-util for things that match this.
- [x] - Update `can-util` to use this.  Add deprecation warning to old modules.
- [x] - Document it.
- [x] - Travis is hooked up
- [x] - [`can-namespace` it](https://github.com/canjs/can-cid/blob/master/can-cid.js)

## API

This module provides a dependency injection container. Modules may `define` a key and specify a default value (which can be static, cached lazy, or dynamic lazy), but other code can `set` and `reset` the value as needed. There is also an event system, for alerting on value changes, both specific to a key and for any key.

#### define( key, value, cache )
__params__
- _key_ `String` - The key value to create.
- _value_ `Any` || `Function` - The default value. If this is a function, its return value will be used.

Defines a new global called `key`, who's value defaults to `value` (if it is not a function), or lazily to the return of `value` (if it is a function). If it is a function, it will be called every time the value is needed.

#### get( key )
- _key_ `String` - The key value to access.

Returns the current value at `key`. If no value has been set, it will return the default value (if it is not a function). If the default value is a function, it will return the output of the function.

`get`ting a key which was not previously `define`d will result in an error.

#### set ( key, value )
- _key_ `String` - The key value to access.
- _value_ `Any` - The new value.

Sets the new value at `key`. Will override previously set values, but preserves the default (see `delete`).

`set`ting a key which was not previously `define`d will result in an error.

#### reset( key )
- _key_ `String` - The key value to access.

Deletes the current value at `key`. Future `get`s will use the default value.

`reset`ting a key which was not previously `define`d will result in an error.

#### on ( [ key, ] observer )
- _key_ `String` - The key value to observe.
- _observer_ `Function` - The observer callback.

Calls `observer` each time the value of `key` is `set` or `reset`. For no key, `observer` will be called each time any value is `set` or `reset`.

`on`ing a key which was not previously `define`d will result in an error. Will not trigger for changes to the return value of lazy defaults.

#### off ( [ key, ] observer )
- _key_ `String` - The key value to observe.
- _observer_ `Function` - The observer callback.

Removes `observer` from future change events for `key`. For no key, removes `observer` from future change events for all keys (must have called `on` with no key).

`off`ing a key which was not previously `define`d will result in an error. `off`ing an observer which was not previously `on`ed for a key will be silently ignored.

#### makeExport( key )
__params__
- _key_ `String` - The key value to access.

Creates an export, for preserving legacy functionality. Returns a function which is `get` (no arguments), `set` (one non-unidentified argument), and `reset` (one unidentified argument).

`makeExport`ing a key which was not previously `define`d will result in an error.

### Setting Default Properties
```javascript
// Define the global key's default value to the window object
globals.define('global', window);
globals.get('window');
```

### Setting a Lazy Property
```javascript
// To make the value lazy you can set it to a function
globals.define('isBrowserWindow', function() {
  return typeof window !== 'undefined' &&
    typeof document !== 'undefined' && typeof SimpleDOM === 'undefined';
});
globals.get('isBrowserWindow'); // will call the provided function every time
```

### Setting a method-like Property
```javascript
// To make the value a method, it must lazily return a function.
globals.define('isRoot', function() {
  return function(pathname) {
    return (pathname || window.location.pathname) === '/';
  };
});

globals.get('isRoot')();
```

### Overwriting/Restoring Properties
```javascript
globals.define('global', window);
globals.set('global', {}); // Overwrite global with an empty object
globals.reset('global'); // Restore to default
globals.get('global') === window;
```

**Comment by justinbmeyer** [comment]
```js
// can-globals/is-browser-window
globals.setDefault("isBrowserWindow", function(){ ...} )

module.exports = globals.makeExport("isBrowserWindow");
```


- Update can-util to point to this:

```
// can-util/js/global

return function(value){
  if(arguments.length) {
    globals.set("global", value)
  } else {
    return globals.get("global");
  }
}
```

**Comment by BigAB** [comment]
Will this be observable, like when globals get set, will an event emit or something?

**Comment by justinbmeyer** [comment]
Maybe `globals.define` or `globals.add` instead of `initialize`?  We are sort of defining the behavior of that property.  We use `define` to mean this other places in canjs.  I'm not sure we have an initialize method anywhere.

**Comment by christopherjbaker** [comment]
I switched to define instead of initialize.

@BigAB: It can certainly be observable, though that ran into a conflict with the use of `delete` (namely that we can't tell when `delete` has happened, so can't emit it). We would need to switch to a syntax more like `globals.get(key)`, `set()`, `restore()`, etc. Since this will be used in so many places at a low level, I would avoid actually depending on `can-observable`, and implement a quick event system instead. How should we handle lazy getters, who's value can change each time it is requested? Should the return be cached and an event be triggered each time the value is different, or should the events only care when `.set()` and `.restore()` is used?

After looking at an example that @justinbmeyer posted, I now see two possibilities for the API structure. Is there a preference for one of these over the other?

```javascript
const globals = require('can-globals');

globals.define('isBrowserWindow', false);
globals.set('isBrowserWindow', true);
if (globals.get('isBrowserWindow')) {
  // do a thing
}
globals.observe('isBrowserWindow', function() {
  // do a thing when it changes
});

globals.observe(function() {
  // do a thing when any changes
});
```
or
```javascript
const globals = require('can-globals');
globals.define('isBrowserWindow', false);

const isBrowserWindow = globals.get('isBrowserWindow');
isBrowserWindow.set(true);
if (isBrowserWindow()) {
  // do a thing
}
isBrowserWindow.observe(function() {
  // do a thing when it changes
});

globals.observe(function() {
  // do a thing when any changes
});
```

**Comment by justinbmeyer** [comment]
The first, but maybe instead of `observe`, just `on` and `off`?

**Comment by christopherjbaker** [comment]
API docs updated accordingly.

**Comment by imaustink** [comment]
Closing as checklist is complete
