### ISSUE TITLE
Should caching be on by default?

### ISSUE THREAD

**Issue by matthewp** [canjs/can-globals#17]
In the old can-util implementations of these globals, the values were not cached. The switch to caching breaks done-ssr in particular, as it depends on getting the fresh value every time a getter is called.

Caching does make sense in a browser environment though.  In tests you would want it off.

I would propose that there be a way to turn caching off globally.

**Comment by justinbmeyer** [comment]
@matthewp I think by introducing events into `can-globals`, `can-globals` must always cache their value.  Otherwise, these events become meaningless as people could listen for changes, but not be notified.  I'm of the opinion we should always cache now.

**Comment by imaustink** [comment]
@justinbmeyer I don't think events would break if we turn off caching, I think the implementation covers that. I would have to double check to be sure.

**Comment by imaustink** [comment]
Events file on [`setKeyValue`](https://github.com/canjs/can-globals/blob/master/can-globals-proto.js#L306) and [`deleteKeyValue`](https://github.com/canjs/can-globals/blob/master/can-globals-proto.js#L268). Caching does not change that.

**Comment by justinbmeyer** [comment]
@imaustink caching does change people's expectations.  I expect that if the state of the app changes, I should get an event.  If someone does:

```
window.document = MAKE_DOC()
```

They would not be notified.  Yet a call to `.get()` would give a different document.   That's confusing.  Instead we should always turn on caching and make the value impossible to change without also notifying people.

**Comment by imaustink** [comment]
@justinbmeyer Okay, I see what you're saying. I hadn't considered someone trying to modify the globals directly.
