### ISSUE TITLE
Returns diffrent results when used directly

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/can-globals#50]
It don't returns the right location after globals.setKeyValue('location', {
  hash:"",
  host:"www.w3schools.com",
  hostname:"www.w3schools.com",
  href:"https://www.w3schools.com/js/js_window_location.asp",
  origin:"https://www.w3schools.com",
  pathname:"/js/js_window_location.asp",
  port:"",
  protocol:"https:"
})

```
var globals = require('can-globals')
var locationObject = {
  hash:"",
  host:"www.w3schools.com",
  hostname:"www.w3schools.com",
  href:"https://www.w3schools.com/js/js_window_location.asp",
  origin:"https://www.w3schools.com",
  pathname:"/js/js_window_location.asp",
  port:"",
  protocol:"https:"
}
globals.setKeyValue('location', locationObject)

globals.getKeyValue('location') // => globals.getKeyValue('global').location
require('can-globals/location/location') // => globals.getKeyValue('global').location
// both should be === locationObject
```
the logic is simply wrong at present i would need to do

```
globals.setKeyValue('global', { ..., location: locationObject })
globals.getKeyValue('location') // => locationObject
require('can-globals/location/location') // => locationObject
```
this would work my PR's are there to fix that

**Comment by frank-dspeed** [comment]
@chasenlehara this is a example issue that i had with can-globals thats why i did the pr's

**Comment by justinbmeyer** [comment]
I believe location is for the location object, not a string url.

**Comment by frank-dspeed** [comment]
@justinbmeyer thats maybe correct but as you can see in all the other stuff like document.js the fail is by design this happens with everything i simply don't got time to write it more accurat at present

**Comment by frank-dspeed** [comment]
@justinbmeyer corrected my example maybe you understand it now better it simply returns the wrong value not the value from setKey as it is wrong written thats why i did the pr's my version from canes is working fine

**Comment by frank-dspeed** [comment]
the logic is simply wrong at present i would need to do

```
globals.setKeyValue('global', { ..., location: locationObject })
```

**Comment by frank-dspeed** [comment]
lets close that issue as this is only a edge which is not on the CanJS Roadmap
